language: ruby
bundler_args: --without development
script: "SPEC_OPTS='--format=d' rake spec"
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
before_install:
  - gem update --system 2.1.11 #  todo: workaround for https://github.com/rubygems/rubygems/pull/763
notifications:
  email: false